//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfClans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public int id { get; set; }
        public int userClanId { get; set; }
        public short actionId { get; set; }
        public string objectChanged { get; set; }
        public string oldValue { get; set; }
        public string newValue { get; set; }
        public System.DateTime addedOn { get; set; }
        public string propertyChanged { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual ClanUser ClanUser { get; set; }
    }
}
