//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfClans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanWar
    {
        public ClanWar()
        {
            this.WarLogs = new HashSet<WarLog>();
            this.WarRankings = new HashSet<WarRanking>();
        }
    
        public int id { get; set; }
        public short warTypeId { get; set; }
        public int clanId { get; set; }
        public string clanVS { get; set; }
        public System.DateTime warStartedOn { get; set; }
        public string note { get; set; }
        public System.DateTime addedOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public string clanVSTag { get; set; }
        public string warNote { get; set; }
        public bool isFinalized { get; set; }
        public short xp { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual WarType WarType { get; set; }
        public virtual ICollection<WarLog> WarLogs { get; set; }
        public virtual ICollection<WarRanking> WarRankings { get; set; }
    }
}
