//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfClans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanUser
    {
        public ClanUser()
        {
            this.ActionLogs = new HashSet<ActionLog>();
            this.UserBlackLists = new HashSet<UserBlackList>();
            this.WarLogs = new HashSet<WarLog>();
            this.WarRankings = new HashSet<WarRanking>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public short userRoleId { get; set; }
        public Nullable<int> clanId { get; set; }
        public string pictureLocation { get; set; }
        public string villageBasePictureLocation { get; set; }
        public string warBasePictureLocation { get; set; }
        public System.DateTime addedOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public string aspnetUserId { get; set; }
        public Nullable<int> clanGroupId { get; set; }
    
        public virtual ICollection<ActionLog> ActionLogs { get; set; }
        public virtual Clan Clan { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<UserBlackList> UserBlackLists { get; set; }
        public virtual ICollection<WarLog> WarLogs { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<WarRanking> WarRankings { get; set; }
    }
}
