//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfClans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanWarPick
    {
        public int id { get; set; }
        public int clanWarId { get; set; }
        public Nullable<short> pickVS { get; set; }
        public string note { get; set; }
        public System.DateTime addedOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public int clanUserId { get; set; }
        public short clanMemberWarPosition { get; set; }
    }
}
