//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfClans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan
    {
        public Clan()
        {
            this.ClanGroups = new HashSet<ClanGroup>();
            this.ClanUsers = new HashSet<ClanUser>();
            this.ClanWars = new HashSet<ClanWar>();
            this.UserBlackLists = new HashSet<UserBlackList>();
            this.Rules = new HashSet<Rule>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string shieldLogoLocation { get; set; }
        public System.DateTime addedOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public string description { get; set; }
        public string tag { get; set; }
        public byte level { get; set; }
    
        public virtual ICollection<ClanGroup> ClanGroups { get; set; }
        public virtual ICollection<ClanUser> ClanUsers { get; set; }
        public virtual ICollection<ClanWar> ClanWars { get; set; }
        public virtual ICollection<UserBlackList> UserBlackLists { get; set; }
        public virtual ICollection<Rule> Rules { get; set; }
    }
}
