//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfClans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarLog
    {
        public int id { get; set; }
        public int clanWarId { get; set; }
        public short clanStars { get; set; }
        public short clanAttacksWon { get; set; }
        public short clanAttacksUsed { get; set; }
        public decimal clanAverageDestruction { get; set; }
        public short clan3Stars { get; set; }
        public short clan2Stars { get; set; }
        public short clan1Stars { get; set; }
        public int clanHeroicDefense { get; set; }
        public int clanHeroicAttack { get; set; }
        public short clanVSStars { get; set; }
        public short clanVSAttacksWon { get; set; }
        public short clanVSAttacksUsed { get; set; }
        public decimal clanVSAverageDestruction { get; set; }
        public short clanVS3Stars { get; set; }
        public short clanVS2Stars { get; set; }
        public short clanVS1Stars { get; set; }
        public string clanVSHeroicDefense { get; set; }
        public string clanVSHeroicAttack { get; set; }
        public string note { get; set; }
        public System.DateTime addedOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    
        public virtual ClanUser ClanUser { get; set; }
        public virtual ClanWar ClanWar { get; set; }
    }
}
