//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfClans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarRanking
    {
        public int id { get; set; }
        public int clanUserId { get; set; }
        public int clanWarId { get; set; }
        public Nullable<int> clanGroupId { get; set; }
        public bool heroicDefense { get; set; }
        public bool heroicAttack { get; set; }
        public short attacksDefended { get; set; }
        public short attacksOn { get; set; }
        public string note { get; set; }
        public System.DateTime addedOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public bool optOut { get; set; }
        public short stars { get; set; }
        public short xp { get; set; }
        public bool attackWin { get; set; }
        public Nullable<System.DateTime> attackOn { get; set; }
    
        public virtual ClanGroup ClanGroup { get; set; }
        public virtual ClanUser ClanUser { get; set; }
        public virtual ClanWar ClanWar { get; set; }
    }
}
