//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfClans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarType
    {
        public WarType()
        {
            this.ClanWars = new HashSet<ClanWar>();
        }
    
        public short id { get; set; }
        public string name { get; set; }
        public byte value { get; set; }
    
        public virtual ICollection<ClanWar> ClanWars { get; set; }
    }
}
